Importing Libraries for the model

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

Data Loading and Preprocessing

In [ ]:
blood_Pressure_Dataset =pd.read_csv('/content/Blood Pressure Dataset.csv')

In [ ]:
# Checking the first 10 rows of the dataset
blood_Pressure_Dataset.head(20)

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders,result
0,1,1,11.28,0.90,34,23,1,1.0,0,45961,48071,NaN,2,1,1,0
1,2,0,9.75,0.23,54,33,1,NaN,0,26106,25333,205.0,3,0,0,1
2,3,1,10.79,0.91,70,49,0,NaN,0,9995,29465,67.0,2,1,0,0
3,4,0,11.00,0.43,71,50,0,NaN,0,10635,7439,242.0,1,1,0,1
4,5,1,14.17,0.83,52,19,0,NaN,0,15619,49644,397.0,2,0,0,0
5,6,0,11.64,0.54,23,48,0,NaN,1,27042,7513,NaN,3,0,0,1
6,7,1,11.69,0.75,43,41,1,1.0,0,38369,32967,206.0,3,1,1,1
7,8,0,12.70,0.41,48,20,0,NaN,0,29781,26749,134.0,2,0,0,0
8,9,0,10.88,0.68,72,44,0,NaN,0,814,9607,99.0,3,0,0,1
9,10,1,14.56,0.61,40,44,0,NaN,0,1278,12715,95.0,2,0,0,0
10,11,1,8.58,0.13,70,28,1,NaN,0,48527,26178,46.0,1,1,1,1
11,12,1,12.77,0.10,35,17,0,NaN,0,22500,43040,382.0,3,1,0,0
12,13,1,16.40,0.45,31,50,0,NaN,1,25639,46997,41.0,3,0,1,1
13,14,0,16.42,0.13,75,40,0,NaN,1,11750,49800,308.0,3,0,1,1
14,15,0,11.97,0.76,18,32,0,NaN,0,14562,18007,NaN,2,1,1,1
15,16,1,10.96,0.10,43,27,1,1.0,0,7329,39018,495.0,1,1,0,0
16,17,1,11.98,0.06,65,28,1,NaN,0,29834,45217,377.0,2,0,0,0
17,18,1,11.60,0.09,61,44,0,NaN,0,49430,36987,153.0,2,0,0,1
18,19,1,8.99,0.17,18,30,1,1.0,0,43934,35603,NaN,3,1,0,0
19,20,1,16.55,0.91,18,38,0,NaN,0,25466,1807,NaN,3,1,1,0

Getting more information about the dataset

In [ ]:
blood_Pressure_Dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Patient_Number                 2000 non-null   int64
 1   Blood_Pressure_Abnormality     2000 non-null   int64
 2   Level_of_Hemoglobin            2000 non-null   float64
 3   Genetic_Pedigree_Coefficient   1908 non-null   float64
 4   Age                            2000 non-null   int64
 5   BMI                            2000 non-null   int64
 6   Sex                            2000 non-null   int64
 7   Pregnancy                      442 non-null    float64
 8   Smoking                        2000 non-null   int64
 9   Physical_activity              2000 non-null   int64
 10  salt_content_in_the_diet       2000 non-null   int64
 11  alcohol_consumption_per_day    1758 non-null   float64
 12  Level_of_Stress                2000 non-null   int64
 13  Chronic_kidney_disease         2000 non-null   int64
 14  Adrenal_and_thyroid_disorders  2000 non-null   int64
 15  result                         2000 non-null   int64
dtypes: float64(4), int64(12)
memory usage: 250.1 KB

In [ ]:
# Checking for missing values in the dataset
blood_Pressure_Dataset.isnull().sum().sum()

1892

In [ ]:
blood_Pressure_Dataset.tail(10)

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders,result
1990,1991,1,11.21,0.01,63,25,0,NaN,1,32903,4540,50.0,3,0,0,0
1991,1992,1,15.53,0.12,22,24,0,NaN,0,48325,16514,NaN,2,1,1,0
1992,1993,1,9.38,0.49,60,39,1,NaN,1,46591,29557,125.0,1,1,1,1
1993,1994,0,9.69,1.00,73,42,1,NaN,1,43344,36230,48.0,3,0,1,0
1994,1995,0,11.07,0.66,58,31,1,NaN,0,38603,22836,379.0,2,0,0,1
1995,1996,1,10.14,0.02,69,26,1,NaN,1,26118,47568,144.0,3,1,0,0
1996,1997,1,11.77,1.00,24,45,1,1.0,1,2572,8063,NaN,3,1,1,0
1997,1998,1,16.91,0.22,18,42,0,NaN,0,14933,24753,NaN,2,1,1,1
1998,1999,0,11.15,0.72,46,45,1,NaN,1,18157,15275,253.0,3,0,1,0
1999,2000,1,11.36,0.09,41,45,0,NaN,0,20729,30463,230.0,1,1,0,1

In [ ]:
fill_data = blood_Pressure_Dataset.fillna(value=1)
fill_data.isnull().sum()

Patient_Number                   0
Blood_Pressure_Abnormality       0
Level_of_Hemoglobin              0
Genetic_Pedigree_Coefficient     0
Age                              0
BMI                              0
Sex                              0
Pregnancy                        0
Smoking                          0
Physical_activity                0
salt_content_in_the_diet         0
alcohol_consumption_per_day      0
Level_of_Stress                  0
Chronic_kidney_disease           0
Adrenal_and_thyroid_disorders    0
result                           0
dtype: int64

In [ ]:
# Checking the Statiscal information about the dataset
fill_data.describe()

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders,result
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.0000,2000.000000,2000.000000
mean,1000.500000,0.493500,11.710035,0.518055,46.558500,30.081500,0.496000,0.878500,0.509500,25254.424500,24926.097000,220.757500,2.012500,0.5050,0.443500,0.479500
std,577.494589,0.500083,2.186701,0.303971,17.107832,11.761208,0.500109,0.326789,0.500035,14015.439623,14211.692586,157.444886,0.823822,0.5001,0.496922,0.499705
min,1.000000,0.000000,8.100000,0.000000,18.000000,10.000000,0.000000,0.000000,0.000000,628.000000,22.000000,0.000000,1.000000,0.0000,0.000000,0.000000
25%,500.750000,0.000000,10.147500,0.250000,32.000000,20.000000,0.000000,1.000000,0.000000,13605.750000,13151.750000,79.000000,1.000000,0.0000,0.000000,0.000000
50%,1000.500000,0.000000,11.330000,0.520000,46.000000,30.000000,0.000000,1.000000,1.000000,25353.000000,25046.500000,212.500000,2.000000,1.0000,0.000000,0.000000
75%,1500.250000,1.000000,12.945000,0.780000,62.000000,40.000000,1.000000,1.000000,1.000000,37382.250000,36839.750000,360.250000,3.000000,1.0000,1.000000,1.000000
max,2000.000000,1.000000,17.560000,1.000000,75.000000,50.000000,1.000000,1.000000,1.000000,49980.000000,49976.000000,499.000000,3.000000,1.0000,1.000000,1.000000

In [ ]:
#  checking the size of the dataset after deleting the missing values
fill_data.shape

(2000, 16)

In [ ]:
# checking for the values of each outcome
fill_data['result'].value_counts()

0    1041
1     959
Name: result, dtype: int64

In [ ]:
# Lable 0 --> People with no high blood pressure
# Lable 1 --> People with  high blood

# Finding the mean of these two outcomes

fill_data.groupby('result').mean()

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
result,,,,,,,,,,,,,,,
0,1022.376561,0.501441,11.810163,0.517531,45.771374,30.491835,0.484150,0.876081,0.511047,25383.031700,24945.885687,217.008646,2.015370,0.508165,0.440922
1,976.752868,0.484880,11.601345,0.518624,47.412930,29.636079,0.508863,0.881126,0.507821,25114.820647,24904.616267,224.826903,2.009385,0.501564,0.446298

Separating the independent variable from the dependent variables

In [ ]:
x= fill_data.drop(columns='result', axis=1)
y= fill_data['result']

In [ ]:
# printing the values stored in x variable
print(x)

      Patient_Number  Blood_Pressure_Abnormality  Level_of_Hemoglobin  \
0                  1                           1                11.28
1                  2                           0                 9.75
2                  3                           1                10.79
3                  4                           0                11.00
4                  5                           1                14.17
...              ...                         ...                  ...
1995            1996                           1                10.14
1996            1997                           1                11.77
1997            1998                           1                16.91
1998            1999                           0                11.15
1999            2000                           1                11.36

      Genetic_Pedigree_Coefficient  Age  BMI  Sex  Pregnancy  Smoking  \
0                             0.90   34   23    1        1.0        0
1                             0.23   54   33    1        1.0        0
2                             0.91   70   49    0        1.0        0
3                             0.43   71   50    0        1.0        0
4                             0.83   52   19    0        1.0        0
...                            ...  ...  ...  ...        ...      ...
1995                          0.02   69   26    1        1.0        1
1996                          1.00   24   45    1        1.0        1
1997                          0.22   18   42    0        1.0        0
1998                          0.72   46   45    1        1.0        1
1999                          0.09   41   45    0        1.0        0

      Physical_activity  salt_content_in_the_diet  \
0                 45961                     48071
1                 26106                     25333
2                  9995                     29465
3                 10635                      7439
4                 15619                     49644
...                 ...                       ...
1995              26118                     47568
1996               2572                      8063
1997              14933                     24753
1998              18157                     15275
1999              20729                     30463

      alcohol_consumption_per_day  Level_of_Stress  Chronic_kidney_disease  \
0                             1.0                2                       1
1                           205.0                3                       0
2                            67.0                2                       1
3                           242.0                1                       1
4                           397.0                2                       0
...                           ...              ...                     ...
1995                        144.0                3                       1
1996                          1.0                3                       1
1997                          1.0                2                       1
1998                        253.0                3                       0
1999                        230.0                1                       1

      Adrenal_and_thyroid_disorders
0                                 1
1                                 0
2                                 0
3                                 0
4                                 0
...                             ...
1995                              0
1996                              1
1997                              1
1998                              1
1999                              0

[2000 rows x 15 columns]

In [ ]:
# printing the values of the target variable y
print(y)

0       0
1       1
2       0
3       1
4       0
       ..
1995    0
1996    0
1997    1
1998    0
1999    1
Name: result, Length: 2000, dtype: int64

Data standardization (Data Encoding)

In [ ]:
scaler = StandardScaler()

scaler.fit(x)

StandardScaler()

In [ ]:
# Transforming the data
standardize_Data = scaler.transform(x)

In [ ]:
# Printing the standardized data
print(standardize_Data)

[[-1.731185    1.01308561 -0.19670848 ... -0.01517697  0.9900495
   1.12017473]
 [-1.72945295 -0.98708341 -0.89656771 ...  1.19898069 -1.0100505
  -0.89271787]
 [-1.7277209   1.01308561 -0.4208464  ... -0.01517697  0.9900495
  -0.89271787]
 ...
 [ 1.7277209   1.01308561  2.37859055 ... -0.01517697  0.9900495
   1.12017473]
 [ 1.72945295 -0.98708341 -0.25617364 ...  1.19898069 -1.0100505
   1.12017473]
 [ 1.731185    1.01308561 -0.16011453 ... -1.22933464  0.9900495
  -0.89271787]]

In [ ]:
x= standardize_Data
y= fill_data['result']

In [ ]:
print(x)
print(y)

[[-1.731185    1.01308561 -0.19670848 ... -0.01517697  0.9900495
   1.12017473]
 [-1.72945295 -0.98708341 -0.89656771 ...  1.19898069 -1.0100505
  -0.89271787]
 [-1.7277209   1.01308561 -0.4208464  ... -0.01517697  0.9900495
  -0.89271787]
 ...
 [ 1.7277209   1.01308561  2.37859055 ... -0.01517697  0.9900495
   1.12017473]
 [ 1.72945295 -0.98708341 -0.25617364 ...  1.19898069 -1.0100505
   1.12017473]
 [ 1.731185    1.01308561 -0.16011453 ... -1.22933464  0.9900495
  -0.89271787]]
0       0
1       1
2       0
3       1
4       0
       ..
1995    0
1996    0
1997    1
1998    0
1999    1
Name: result, Length: 2000, dtype: int64

Splitting our data into train and test data

In [ ]:
x_train, x_test, y_train, y_test =train_test_split(x,y, test_size=0.1, stratify=y, random_state=2)

In [ ]:
# Checking the shape of our origin x, x_train and x_test
print(x.shape, x_train.shape, x_test.shape)

(2000, 15) (1800, 15) (200, 15)

Training the model

1. Using Support Vector Classifier

In [ ]:
classifier =svm.SVC(kernel='linear')

In [ ]:
# training the support vector Machine classifier
classifier.fit(x_train, y_train)

SVC(kernel='linear')

In [ ]:
# Model Evaluation

 1. Accuracy Score For SVM model

In [ ]:
# The Accuracy on the training data
x_train_prediction =classifier.predict(x_train)
training_Data_Accuracy = accuracy_score(x_train_prediction, y_train)

In [ ]:
# printing the accuracy score of the training data
print('The Accuracy Score of the training data is:',training_Data_Accuracy )

The Accuracy Score of the training data is: 0.525

In [ ]:
# The Accuracy on the test data
x_test_prediction =classifier.predict(x_test)
test_Data_Accuracy = accuracy_score(x_test_prediction, y_test)

In [ ]:
# printing the accuracy score of the test data
print('The Accuracy Score of the test data is:',test_Data_Accuracy )

The Accuracy Score of the test data is: 0.475

Developing the predictive system

In [ ]:
input_data =(23,0,11.19,0.75,71,41,1,1,1,19422,21537,223,3,0,0)
# changing the input data to a numpy array
input_data_as_array =np.asarray(input_data)

# reshaping the arraay as we are predicting for one instance
input_data_reshape = (input_data_as_array.reshape(1,-1))

# Standardizing the input data

std_data = scaler.transform(input_data_reshape)
print(std_data )

# Making the prediction
prediction = classifier.predict(std_data)
print(prediction)

if(prediction[0]==0):
   print('The person is not having High blood pressure')
else:
  print('The person is having High blood pressure')
print()
print()

[[-1.69307988 -0.98708341 -0.23787667  0.76324185  1.42903044  0.92858067
   1.00803226  0.37189236  0.98117712 -0.41624689 -0.23853208  0.01424664
   1.19898069 -1.0100505  -0.89271787]]
[1]
The person is having High blood pressure

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(